### ISSUE TITLE
❓Something about Embedded Notes and Pushed down Content

### ISSUE THREAD

**Issue by ThisUserNeedsHelp** [jparkerweb/pixel-banner#85] opened 2024-12-20 21:29 UTC
Issue 81 had nothing to do with Note Titles.

**Comment by jparkerweb** [comment] 2024-12-21 04:47
Lol @ThisUserNeedsHelp ,
I think you need to give us some screenshots and better yet an example vault.

We can't read your mind 🤷

**Comment by jparkerweb** [comment] 2024-12-21 04:53
It's seems @ThisUserNeedsHelp isn't a serious username.  You might get better support by joining our Discord.

Otherwise please leave "detailed" notes on what your real issue is.

We take all submitted issues seriously but require reproducible steps or the issue will be closed as "cannot be reproduced", thank you 🍆

**Comment by ThisUserNeedsHelp** [comment] 2024-12-21 19:48
<img width="574" alt="Screenshot 2024-12-21 at 2 43 33 PM" src="https://github.com/user-attachments/assets/2eb8ef1f-c6e6-49c6-ac42-be161a94bb3c" />

**Comment by jparkerweb** [comment] 2024-12-22 00:15
@ThisUserNeedsHelp I am sorry but I am unable to reproduce this:
![image](https://github.com/user-attachments/assets/f932904d-0c58-4a6b-a72a-05f0058e0670)

**Comment by jparkerweb** [comment] 2024-12-22 00:17
@ThisUserNeedsHelp you can download the sample vault for the plugin here and see if you see the same thing:
https://github.com/jparkerweb/pixel-banner/blob/main/example-vault.zip

As suggested, please upload a sample vault that reproduces your issues so I can take a look and address.

Thank you 😜

**Comment by jparkerweb** [comment] 2024-12-22 00:20
maybe I am misunderstanding your issue.... embedded notes have a little different layout than the parent/normal note.  
I can maybe add an option to expand on your "Hide the Children" theme and have an option to "hide" banners for embedded notes?

please spell out what you are looking for....

**Comment by ThisUserNeedsHelp** [comment] 2024-12-22 13:24
I do not have anything activated in the Folder Image settings.

I do not know the procedure for sending a vault.I do not have Obsidian Sync.

I am guessing that "Hide The Children" would resolve the problem if it is NOT a folder image setting. I am not using a folder image.

**Comment by jparkerweb** [comment] 2024-12-22 15:59
Create a new Obsidian vault showing the issue.  Zip up the entire vault into one zip file and attach it to this issue.

**Comment by ThisUserNeedsHelp** [comment] 2024-12-22 18:51
[Demo.zip](https://github.com/user-attachments/files/18222944/Demo.zip)

**Comment by jparkerweb** [comment] 2024-12-22 21:49
fix incoming (with a "Hide the Children, PART II" option 🤣)

![image](https://github.com/user-attachments/assets/d1124af0-d020-4ff6-8e71-d380c87240da)

![image](https://github.com/user-attachments/assets/43dcfd69-a48f-4cd7-ac6f-8ca574f4e070)

![image](https://github.com/user-attachments/assets/6e66307c-6ea1-4c46-863a-e6aa74a18cfb)

**Comment by jparkerweb** [comment] 2024-12-22 21:54
![image](https://github.com/user-attachments/assets/236f6fb4-1262-4ce1-bc49-3ca9402448b4)

**Comment by ThisUserNeedsHelp** [comment] 2024-12-23 01:19
I am sure that whatever you are talking about works. But the problem is that such an option does not show up in my Pixel Banner options.

It is not under General.
It is not under Custom Field Names.
It is not under API settings.
And the attached screen shot shows what is in Folder Images

<img width="709" alt="Screenshot 2024-12-22 at 8 18 01 PM" src="https://github.com/user-attachments/assets/fabe94ad-242c-4442-b644-7c7db2590767" />

**Comment by jparkerweb** [comment] 2024-12-23 01:34
It isn't published yet, LOL

just doing a new release now (I was giving you a heads up on the fix coming)

![pixel-banner-v2 16 0](https://github.com/user-attachments/assets/ea7ee7a7-b7cf-4a9f-82d6-e71bd0f65c89)

Go ahead and update the plugin NO@

**Closed** 2024-12-23 01:36 UTC
Labels: bug

**Comment by ThisUserNeedsHelp** [comment] 2024-12-23 14:22
It is working properly. Thank you.
